- hosts: localhost
  gather_facts: false
  tasks:
    - name: set ssh key path facts
      set_fact:
        private_key: "{{ lookup('env', 'HOME') }}/.ssh/{{ tripleo_admin_user }}-id_rsa"
        public_key: "{{ lookup('env', 'HOME') }}/.ssh/{{ tripleo_admin_user }}-id_rsa.pub"
      run_once: true
    - name: stat private key
      stat:
        path: "{{ private_key }}"
      register: private_key_stat
    - name: create private key if it does not exist
      shell: "ssh-keygen -t rsa -q -N '' -f {{ private_key }}"
      no_log: true
      when:
        - not private_key_stat.stat.exists
    - name: stat public key
      stat:
        path: "{{ public_key }}"
      register: public_key_stat
    - name: create public key if it does not exist
      shell: "ssh-keygen -y -f {{ private_key }} > {{ public_key }}"
      when:
        - not public_key_stat.stat.exists

- hosts: overcloud
  gather_facts: false
  become: true
  pre_tasks:
    - name: Get local private key
      slurp:
        src: "{{ hostvars['localhost']['private_key'] }}"
      register: private_key_get
      delegate_to: localhost
      no_log: true
    - name: Get local public key
      slurp:
        src: "{{ hostvars['localhost']['public_key'] }}"
      register: public_key_get
      delegate_to: localhost
  roles:
    - role: tripleo_create_admin
      tripleo_admin_user: "{{ tripleo_admin_user }}"
      tripleo_admin_pubkey: "{{ public_key_get['content'] | b64decode }}"
      tripleo_admin_prikey: "{{ private_key_get['content'] | b64decode }}"
      no_log: true