FROM registry-proxy.engineering.redhat.com/rh-osbs/rhosp17-openstack-tripleoclient:17.1_20230620.2

USER root
WORKDIR /tripleo-ipa-patch
RUN GIT_SSL_NO_VERIFY=1 git clone https://code.engineering.redhat.com/gerrit/ansible-tripleo-ipa.git
WORKDIR ansible-tripleo-ipa/
RUN git checkout remotes/origin/rhos-17.1-patches
RUN git config --global user.email "you@example.com"
RUN git config --global user.name "Your Name"
RUN git fetch https://review.opendev.org/x/tripleo-ipa refs/changes/27/886727/4 && git cherry-pick FETCH_HEAD
RUN python3 setup.py install
USER cloud-admin
