---
ocp_ai_discovery_iso: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{{ ocp_version }}/latest/rhcos-live.x86_64.iso"
ocp_ai_onprem_env: "{{ lookup('url', 'https://raw.githubusercontent.com/openshift/assisted-service/master/onprem-environment', wantlist=True) }}"

# this address needs to be reachable from IPMI/iDRAC if BM worker is used 
ocp_ai_discovery_iso_server: 192.168.111.1

ocp_ai_external_dns:
  - 10.11.5.19
  - 10.38.5.26
  - 10.10.160.2
  - 10.5.30.160

# ocp_ai_service_repo: defaults to "https://github.com/sonofspike/assisted-service-onprem.git"
# ocp_ai_service_branch: defaults to "feb00ba10823ab04ec489a05ce8eb543ec688fda"
# ocp_ai_ansible_repo: defaults to "https://github.com/openstack-k8s-operators/cluster_mgnt_roles.git"
# ocp_ai_ansible_branch: defaults to "master"

ocp_ai_bm_bridge_master_mac_prefix: 3c:fd:fe:78:ab:0
ocp_ai_bm_bridge_worker_mac_prefix: 3c:fd:fe:78:ab:1
ocp_ai_prov_bridge_master_mac_prefix: 3c:fd:fe:78:cd:0
ocp_ai_prov_bridge_worker_mac_prefix: 3c:fd:fe:78:cd:1

# ocp_ai_sushy_port: defaults to "8082"

# ocp_ai_service_store_dir: defaults to "/opt/assisted-service"
# ocp_ai_service_port: defaults to "8090"

ocp_ai_libvirt_storage_dir: /var/lib/libvirt/images
