---
- hosts: convergence_base
  become: true

  tasks:
  - name: Include variables
    include_vars: vars/default.yaml

  - name: Remove libvirt data disks (if any)
    file:
      path: "{{ ocp_storage_data_dir }}"
      state: absent

  - name: Restart libvirt
    service:
       name: libvirtd
       state: restarted
