---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - name: Set combined osp dict
    set_fact:
      osp: "{{ osp_defaults | combine((osp_release_defaults | default({})), recursive=True) | combine((osp_local | default({})), recursive=True) }}"

  # Create caphadm user, sshkeys
  # TODO: allow OSPdO deploy with a custom playbook abspath etc... for tripleo-ansible playbooks
  #       right now it assumes playbook path is relative to config download dir
  #       In the meantime use a custom playbook that works with the OSPdO inventory
  - name: copy ceph-admin-user-playbook to openstackclient
    shell: |
      #!/bin/bash
      oc cp -n openstack {{ playbook_dir }}/files/osp/ceph-admin-user-playbook.yml openstackclient:/home/cloud-admin/ceph-admin-user-playbook.yml
    environment: &oc_env
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: run ceph-admin-user-playbook playbook via openstackclient
    shell: |
      oc rsh -n openstack openstackclient <<"EOF_RSH"
        ansible-playbook -i /home/cloud-admin/ctlplane-ansible-inventory -e tripleo_admin_user=ceph-admin -e distribute_private_key=true /home/cloud-admin/ceph-admin-user-playbook.yml
      EOF_RSH
    environment:
      <<: *oc_env

# Upgrade Prepare for ceph upgrade

- name: Generate Ceph Upgrade custom config
  import_playbook: osp_custom_config.yaml
  vars:
    config_generator_name: ceph-upgrade
    custom_config_name: ceph-upgrade
    custom_config_action: ceph-upgrade
    ceph_tag_override: "{{ ceph_5_tag }}"
    ceph_image_override: "{{ ceph_5_image|default(osp.ceph_image) }}"

- name: Ceph Upgrade Prepare config generate
  import_playbook: config_generator.yaml
  vars:
    custom_config_name: ceph-upgrade
    config_generator_name: ceph-upgrade
    config_generator_action: ceph-upgrade

# Ceph 4->5 upgrade

- name: Ceph Upgrade deployment
  import_playbook: osp_deployment.yaml
  vars:
    config_generator_name: ceph-upgrade
    deploy_name: ceph-upgrade
    deploy_mode: externalUpgrade
    deploy_advanced_settings:
      skipTags:
        - ceph_health
        - opendev-validation
        - ceph_ansible_remote_tmp
      tags:
        - ceph
        - facts

- name: Ceph Upgrade packages
  import_playbook: osp_deployment.yaml
  vars:
    config_generator_name: ceph-upgrade
    deploy_name: ceph-upgrade
    deploy_mode: upgrade
    deploy_advanced_settings:
      limit: ceph_osd,ceph_mon,Undercloud
      playbooks:
        - upgrade_steps_playbook.yaml
      skipTags:
        - ceph_health
        - opendev-validation
        - ceph_ansible_remote_tmp
      tags:
        - setup_packages

- name: Ceph Upgrade cephadm adoption
  import_playbook: osp_deployment.yaml
  vars:
    config_generator_name: ceph-upgrade
    deploy_name: ceph-upgrade
    deploy_mode: externalUpgrade
    deploy_advanced_settings:
      skipTags:
        - ceph_health
        - opendev-validation
        - ceph_ansible_remote_tmp
      tags:
        - cephadm_adopt
