---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - name: Set combined osp dict
    set_fact:
      osp: "{{ osp_defaults | combine((osp_release_defaults | default({})), recursive=True) | combine((osp_local | default({})), recursive=True) }}"
  - name: Upgrade openstackcontrolplane release
    environment: &oc_env
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
    shell: |
      oc patch openstackcontrolplane -n openstack overcloud --type=json -p="[
        {'op': 'replace', 'path': '/spec/openStackRelease', 'value': '{{ osp.release }}'}
      ]"

- name: Disable fencing
  import_playbook: osp_disable_fencing.yaml

# TODO: What do we need to do for external ceph?
# Looks like we need to stay with ceph-ansible to run some tasks then switch to cephadm?
- name: Generate Upgrade custom config
  import_playbook: osp_custom_config.yaml
  vars:
    custom_config_name: upgrade
    custom_config_action: upgrade
    custom_config_extrafeatures: [ "upgrade" ]

- name: Upgrade Prepare config generate
  import_playbook: config_generator.yaml
  vars:
    custom_config_name: upgrade
    config_generator_name: upgrade
    config_generator_action: upgrade

- name: Upgrade overcloud deployment
  import_playbook: osp_deployment.yaml
  vars:
    config_generator_name: upgrade
    deploy_name: upgrade
    deploy_mode: upgrade

# TODO: controllers RHEL8->RHEL9 upgrade

# TODO: computes RHEL8->RHEL9 upgrade or multi-rhel
# BLOCKER? multi-rhel needs to "move" computes to different tripleo role

# TODO: final steps
